id: P54FAABA7
initial_creation_type: input
source_metadata:
  Title: Atisha-virachita Ekadasagrantha
  Editor: Negi, R.C.
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1992'
  Mahāyānapathasādhanasaṅgrahaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:43:23.072510'
last_modified_at: '2022-03-08T16:43:23.072518'
